eureka:
  client:
    service-url:
      defaultZonn: http://localhost:8761/erueka/, http://localhost:8762/erueka/
spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/take_away?chacterEncoding=utf-8&useSSL=false
    username: root
    password: root
env: dev